### ISSUE TITLE
Add smoke testing scripts

### ISSUE THREAD

**Issue by copejon** [redhat-et/microshift#100]
Create a set of smoke tests to be executed against a running Microshift cluster.  Each test should encapsulate it's workflow and manifests as an isolated unit of work, e.g. [./test/pv-test.sh](https://github.com/redhat-et/microshift/blob/main/test/pv-test.sh).  The test should clean up after itself on completion.

The manifests should define common openshift workloads (i.e. create a deployment, wait for pods to run; define a pod and pvc, wait for the pvc to provision and pod to run; etc) and produce a quantifiable pass/fail result.  The test script will be responsible for deploying the manifests, monitoring their state, and reporting a pass/fail as well as logs relevant to the components being tested.

Tests to add:

- [ ] Pod scaling:  increasing or decreasing the replicas value of a Deployment scales pods accordingly
- [ ] Cluster Networking: create a Pod and associated Service, ensure Pod is reachable via the Service endpoint
- [ ] TDB
- [ ] ...

**Comment by cooktheryan** [comment]
I think kuttl would be a good tool for this. 


If no one takes this by the time I return from PTO I'll take it

**Comment by copejon** [comment]
[Kuttl](https://kuttl.dev/) looks like a good fit for this.  Are you still interesting in kick-starting this issue @cooktheryan?

**Comment by cooktheryan** [comment]
@copejon yep hopefully that will be my tomorrow task

**Comment by copejon** [comment]
Microshift will not rely on home baked scripts for e2e testing and switch instead to origin/openshift-tests to execute conformance tests.  This is being integrated into CI by PR https://github.com/openshift/release/pull/21499
