### ISSUE TITLE
Add SElinux policies to install script

### ISSUE THREAD

**Issue by oglok** [redhat-et/microshift#123]
Add and test selinux policies to allow microshift run in a system with SElinux in enforcing mode.

**Comment by cooktheryan** [comment]
Hope this helps
https://gist.github.com/cooktheryan/664d5ecb37052c7576d700632b313ca9

**Comment by mykaul** [comment]
I think there should be a warning somewhere (docs would be a good start) regarding currently disabling selinux.

**Comment by cooktheryan** [comment]
/assign cooktheryan

I will regret this
