### ISSUE TITLE
Migrate `logrus` to `klog` making microshift logging level compatible with embedded upstream components.

### ISSUE THREAD

**Issue by husky-parul** [redhat-et/microshift#134]
`Microshift` currently uses `logrus`. However, `logrus` log leveling is incompatible with `klog`, which is used in the embedded upstream (k8s/openshift) components.

**Comment by husky-parul** [comment]
@fzdarsky 
Is it ok to start on it?

**Comment by copejon** [comment]
cc @rootfs

**Comment by fzdarsky** [comment]
@husky-parul yes, now that #153 merged (and considering there'll be more refactoring needed as in #161) ok to start if you haven't already. Please assign yourself to the issue in that case.

While at it, would be great if you could figure out the appropriate v level (as per [0]) and also have a look at the logging of embedded services once more: they somehow stubbornly refuse to log to files.

[0] https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md

**Comment by husky-parul** [comment]
Seems like I do have the privilege to self assign.

**Comment by fzdarsky** [comment]
Oh? k, no problem, just assigned it to you.
