### ISSUE TITLE
CLI option to distinguish boostrap from restart

### ISSUE THREAD

**Issue by rootfs** [redhat-et/microshift#137]
Currently the boostrapping is inherited in all bootup, we need to have an option to distinguish the first time bootup and restart.

**Comment by fzdarsky** [comment]
This needs some design discussion as it'll impact the UX resp. the cluster provisioning workflow.

For example, we wouldn't want to add a `--firstboot` config flag, as this would make use as systemd service hard and be an unnecessary hoop for users running manually, too. Instead, just auto-detect that the node has been bootstrapped before (plus possibly make it easy to explicitly reset/rebootstrap). For the second and later cluster nodes, bootstrapping will likely involve retrieving config/artifacts from the running cluster.

It may make sense to wait with this until after the refactoring of the start-up logic.

**Comment by copejon** [comment]
@rootfs is this issue still relevant?

**Comment by mangelajo** [comment]
Closing it for now
