### ISSUE TITLE
How can I use internal image registry with Microshift?

### ISSUE THREAD

**Issue by tadayosi** [redhat-et/microshift#138]
Hi team,

I find this project very useful and is trying to use it with my project, but as soon as running it I noticed an image-registry is not available. Apparently by design Microshfit doesn't install any operators by default so no Image Registry Operator nor `configs.imageregistry.operator.openshift.io/cluster` exist either.

Any advices on how to use image registry with Microshift?  Is there a plan to provide an easy way to install and enable it?

**Comment by rootfs** [comment]
@tadayosi thank you for the feedback, the project is still in the early stage. The goal is to keep the footprint small, so we don't choose install operators unless there is an absolute need. We'll look into image registry in the next step. Your input and help is highly welcome.

**Comment by rootfs** [comment]
opened an issue #144

**Comment by fzdarsky** [comment]
This is a documentation issue, so closing this in favour of redhat-et/microshift-documentation#74.
