### ISSUE TITLE
install error on subscription-manager register (This system is already registered. Use --force to override)

### ISSUE THREAD

**Issue by guymguym** [redhat-et/microshift#140]
Hi
I failed running the install script on RHEL 8.4:

```
[root@server ~]# curl -sfL https://raw.githubusercontent.com/redhat-et/microshift/main/install.sh | sh -
This system is already registered. Use --force to override
```

Running with -x:
```
[root@server ~]# curl -sfL https://raw.githubusercontent.com/redhat-et/microshift/main/install.sh | sh -x -
+ set -e -o pipefail
++ curl -s https://api.github.com/repos/redhat-et/microshift/releases
++ grep tag_name
++ cut -d '"' -f 4
+ VERSION=v0.2
+ get_distro
++ egrep '^(ID)=' /etc/os-release
++ sed 's/"//g'
++ cut -f2 -d=
+ DISTRO=rhel
+ [[ rhel != @(rhel|fedora|centos) ]]
+ get_arch
++ uname -m
+ ARCH=x86_64
+ '[' rhel = rhel ']'
+ register_subs
+ sudo subscription-manager register --auto-attach
This system is already registered. Use --force to override
```

I bypassed it by saving the script, and editing it to comment out this line.
I am not familiar with the subscription-manager enough to suggest a PR, but if you can guide me on what would be the right approach I would be able to suggest a fix.

Thanks!

**Comment by copejon** [comment]
@oglok If you're satisfied the merge solves the issue, can we close this?

**Comment by guymguym** [comment]
@oglok I see you added `||` so on one hand if register fails it will indeed continue to enable the repo, but what if register succeeds? will that skip enabling the repo because the first call is true?

**Comment by oglok** [comment]
@guymguym Correct! I didn't push the latest change where I had `echo ""` after the `||`. My bad! Thanks for pointing this out.

**Comment by guymguym** [comment]
Hey @oglok This issue seems to still be there in install.sh -
https://github.com/redhat-et/microshift/blob/9762856a560cf72ad5b65df99ef341c9a40de684/install.sh#L32

I see in the history of the file that you added `||` (without the echo) but then the next commit e711417cd9c8898d0528c71cef1cdee1518c9121 replaced the entire block around it and reverted your change.

**Comment by guymguym** [comment]
Oh and another followup issue is that since the script is running with `set -e -o pipefail` skipped the systemd service install if the apply_selinux_policy() commands had any unhandled failure.
I ended up disabling the `set -e ...` option to make it work, which is the same thing that also happened here in the subscription-manager unhandled error.
Are you guys sure that using set -e is a good idea?
