### ISSUE TITLE
[RFE] Switch to ubi-minimal

### ISSUE THREAD

**Issue by e-minguez** [redhat-et/microshift#141]
https://github.com/redhat-et/microshift/blob/7a42d43c9f3af4d066fa8aa9c71776bd2b08f13a/images/build/Dockerfile#L28

Not sure about the real size but I guess it worth trying. [More info about ubi-minimal](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index#con_understanding-the-ubi-minimal-images_assembly_types-of-container-images)
Note there is also ubi-micro but it doesn't include any package manager.

**Comment by rootfs** [comment]
yum install on ubi-minimal is tricky. I haven't got it done right, but if you can figure how to install `iptables` on ubi-minimal, please open an PR and we are happy to merge it.
