### ISSUE TITLE
CLI option to set API server port

### ISSUE THREAD

**Issue by rootfs** [redhat-et/microshift#142]
Currently the API port `6443` is hardcoded. This becomes an issue when the port is taken (especially when multiple microshift clusters are running on the same host). Need to parameterize API server port.

**Comment by fzdarsky** [comment]
In how far is this issue limited to the API port? Are you assuming containerized deployments (where most ports would be node or cluster scoped) or host deployments?

**Comment by rootfs** [comment]
thank you @osilkin98 
preferably, if we can set the port via an env var (in addition to existing config file mechanism), that'll be great. The use case is that when running a containerized microshift on Mac/Windows, env var is the best way

**Comment by osilkin98** [comment]
When the API port is defined in the config, environment, and passed in through the CLI, what should the order of priority be when the value differs in all three cases?

**Comment by fzdarsky** [comment]
The order in which all config gets applied is defaults --> config.yaml --> env vars --> command line args, i.e. if all 3 have different values, command line arg (which is most explicit) wins. See:
See https://github.com/redhat-et/microshift/blob/c1011339c612f41ac32dcfa07ae9e80860d25956/pkg/config/config.go#L183-L201.

**Comment by osilkin98** [comment]
Should we decouple the port from the rest of the URI in `ClusterConfig.URL`? Currently the port gets baked into the URL, and customizing the port requires disassembling the string and appending the new port. While this works, it is prone to breaking if the order variables are processed is changed, as well as making it difficult to work with when the values are provided as environment variables.  

It doesn't seem like `ClusterConfig.URL` really gets written to outside of the initializing stage, so maybe the path could be assembled after Microshift decides which service port to use.
