### ISSUE TITLE
install.sh not working on RHEL 8.4

### ISSUE THREAD

**Issue by fullprocess** [redhat-et/microshift#160]
OS Details
------------------------------------------------------------
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"

Issue
------------------------------------------------------------
I'm attempting to install on an AWS EC2 instance running RHEL 8.4. I successfully ran 
`curl -sfL https://raw.githubusercontent.com/redhat-et/microshift/main/install.sh > install.sh`. However, when executing install.sh, it gets stuck (hangs) on line 167 (`register_subs`) below:
```
# Script execution
get_distro
get_arch
if [ $DISTRO = "rhel" ]; then
    register_subs
fi
```

Within the function `register_subs()`, the command `sudo subscription-manager status` seems to be the one that's hanging. When I run this command in my shell myself, it displays 
```
[root@ip-166-28-35-54 ec2-user]# sudo subscription-manager status
+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Unknown
```
and hangs until I CTRL+C.

**Comment by rootfs** [comment]
i don't have a rhel to test right now but it looks there are [previous subscription-manager hang incidents](https://access.redhat.com/solutions/2202931). 

As a workaround, you might try add a `timeout` command for [this](https://github.com/redhat-et/microshift/blob/main/install.sh#L29) line

**Comment by fullprocess** [comment]
Thanks @rootfs, but even something like `SOMEVAR=$(sudo timeout 3 subscription-manager status)` fails to set SOMEVAR because I think when `timeout` kills the command it also cancels the setting of the variable

**Comment by rootfs** [comment]
that's fine, [the line below](https://github.com/redhat-et/microshift/blob/main/install.sh#L30) takes care of that, but again it runs subscription-manager, which will hang...

i suggest you fix the hang issue first, maybe [this one](https://access.redhat.com/solutions/189533) can help
