### ISSUE TITLE
Refactor embedded services to service interface and manager

### ISSUE THREAD

**Issue by fzdarsky** [redhat-et/microshift#161]
With #152 and #153 we've started restructuring MicroShift such that embedded services (etcd, kube-apiserver, etc.) have their logic self-contained (one file per service), conform to a common Service interface, and using a service manager to implement startup dependencies and cancellation consistently.

So far, only etcd and kube-apiserver have been migrated over. We need all other components to be migrated, too:
* kube-controller-manager
* kube-scheduler
* openshift-preparation (namespaces, SCCs, CRDs, etc.)
* openshift-apiserver
* openshift-controller-manager
* kubelet
* kubeproxy
* component-loader (see #144)

Services can likely be migrated over one-by-one in multiple PRs / by multiple people.

**Comment by fzdarsky** [comment]
Note that some services currently hardcode the SIGTERM signal handler to the stop channel in the upstream code and that patches in `/hack/patches` patch out from our vendored packages. When refactoring kube-scheduler, kube-controller-manager, and klusterlet (following the example of kube-apiserver), please therefore ensure to test without those patches applied (see also #163).

**Comment by oglok** [comment]
I will work on porting the kube-scheduler to the new service manager framework.

**Comment by sallyom** [comment]
I'll work on porting kube-controller-manager let's see how far I get b4 PTO

**Comment by husky-parul** [comment]
> I will work on porting the kube-scheduler to the new service manager framework.

Oh I assigned that to myself. I will un-assign myself. Feel free to take it https://github.com/redhat-et/microshift/issues/199

**Comment by fzdarsky** [comment]
Addressed by #199, #200, #201, #229, #239.
