### ISSUE TITLE
Pre-loading container images into CRI-O

### ISSUE THREAD

**Issue by fzdarsky** [redhat-et/microshift#162]
MicroShift needs a built-in mechanism to pre-load container images into nodes' CRI-O instances so that it can bootstrap its component services a) without network connectivity and b) without local image registry.

The mechanism should monitor `/var/lib/microshift/images` for oci-archives or multi-image docker-archives as produced by `podman save` and pre-load them into CRI-O on cluster initialization or whenever that directory changes.

Requirements:
* MUST NOT change image digests, so the images can be referenced from K8s manifests by digest, too.
* MUST be compatible with multi-arch images and having multiple tarballs/versions of images (e.g. for updates)
* SHOULD unzip tarballs if necessary.
* SHOULD support deleting pre-loaded images from `/var/lib/microshift/images` and subsequently pruning from CRI-O.

**Comment by cooktheryan** [comment]
@fzdarsky do you have a minimum list of images we would want to ship?

**Comment by rootfs** [comment]
@cooktheryan You can start with `kubect get pods -A |grep image` to filter out the actively running images.

**Comment by cooktheryan** [comment]
@fzdarsky @rootfs I wanted to get your input on this before writing the code in go. This is what I am thinking (in bash) 
```
for i in `sudo ls /var/lib/microshift/images`; do sudo lsof $i && sudo podman load $i && sudo rm -rf $i ; done
```

We start the process on a predefined schedule and log to the microshift log file. We want to do lsof or something similar to make sure the file isn't being written to at the time of us attempting to load. Once loading we would remove the file.

**Comment by rootfs** [comment]
@cooktheryan what does `podman load` for? do you mean running `podman load` while starting microshift?

**Comment by cooktheryan** [comment]
The for loop was just the example of dynamically listing the items within the directory. For the loading before starting microshift we would need to make sure the deployments did not attempt to begin before the images were loaded
