### ISSUE TITLE
Refactor OCPControllerManager to conform to the internal service manager

### ISSUE THREAD

**Issue by husky-parul** [redhat-et/microshift#239]
#### Design Document Link

PR: #
Parent issue #161

**Comment by husky-parul** [comment]
@rootfs @fzdarsky 
What is the intent of `util.Must(m.AddService(controllers.NewOpenShiftPrepJob()))` in run.go ?

**Comment by fzdarsky** [comment]
Yeah, it was a placeholder for a service that runs to completion doing the PrepareOCP work. Just wondering, though, whether it logically belongs into one of the other services.
