### ISSUE TITLE
[BUG] <Documentation> OS required version not stated

### ISSUE THREAD

**Issue by hguerrero** [redhat-et/microshift#259]
#### What happened:

When following the README.md documentation there is no mention of the required minimum version for the OS.

#### What you expected to happen:

For the text to include the required OS version.

#### How to reproduce it (as minimally and precisely as possible):

1. '...'
2. '...'

#### Anything else we need to know?:

When using RHEL the minimum required version is 8.

#### Environment:
- Microshift version (use `microshift version`):
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by rootfs** [comment]
I've tested microshift binary on Fedora 33 and 34, CentOS 8 stream, and RHEL 8. The all-in-one containerized microshift can run on linux, windows, and mac. 

More info is surely very helpful and welcome.

**Comment by tadayosi** [comment]
FYI I have managed to run Microshift on CentOS 7 (tested only v0.2 pre-release) and Ubuntu 20.04 (latest microshift version) after tweaking the `install.sh`. See #263 for a known issue.

**Comment by tadayosi** [comment]
FYI my pull req for ubuntu support #271
