### ISSUE TITLE
[BUG] Run with podman machine

### ISSUE THREAD

**Issue by guillaumerose** [redhat-et/microshift#272]
#### What happened:

It doesn't start properly. 

```
$ kubectl get pods -A
NAMESPACE                       NAME                                  READY   STATUS              RESTARTS   AGE
kube-system                     kube-flannel-ds-qfmpg                 0/1     Init:0/1            0          24m
kubevirt-hostpath-provisioner   kubevirt-hostpath-provisioner-5jwfp   0/1     ContainerCreating   0          24m
openshift-dns                   dns-default-wgmmc                     0/3     ContainerCreating   0          24m
openshift-ingress               router-default-78d9fc46bb-xn44x       0/1     ContainerCreating   0          25m
openshift-service-ca            service-ca-66bcdfc59-6j998            0/1     Pending             0          25m
```

#### What you expected to happen:

It starts

#### How to reproduce it (as minimally and precisely as possible):

1. podman machine init
2. podman machine start
3. podman machine ssh
4. sudo -s
5. setsebool -P container_manage_cgroup true
6. podman volume create ushift-vol
7. podman run -d --rm --name ushift --privileged -v /lib/modules:/lib/modules -v ushift-vol:/var/lib --hostname ushift -p 6443:6443 rootfs/ushift 

#### Environment:
- Microshift version (use `microshift version`): rootfs/ushift:latest
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`): macOS with podman machine (brew install podman)
- Kernel (e.g. `uname -a`): Linux localhost 5.13.13-200.fc34.x86_64 #1 SMP Thu Aug 26 17:06:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Others: It uses Fedora CoreOS

**Comment by rootfs** [comment]
@guillaumerose i don't maintain `docker.io/rootfs/ushift` any more. The latest official release is at `quay.io/microshift/microshift:4.7.0-0.microshift-2021-08-31-224727-linux-amd64` or if you run the [all-in-one](https://github.com/redhat-et/microshift/tree/main/hack/all-in-one) mode, the image is at `quay.io/microshift/microshift:4.7.0-0.microshift-2021-08-31-224727-aio-linux-amd64`

**Comment by guillaumerose** [comment]
Thanks! With the second image, it works perfectly. 

It is really really nice. Awesome!

**Comment by guillaumerose** [comment]
I gathered the instructions here if you are interested: https://gist.github.com/guillaumerose/66417a29135cc980ca4181bec8f2f2a5

Works out of the box with podman without Docker Desktop :)

**Comment by rootfs** [comment]
@guillaumerose those instructions are surely PR worthy, looking forward
