### ISSUE TITLE
[Enhancement]: Provide RPM for MicroShift SELinux policies

### ISSUE THREAD

**Issue by fzdarsky** [redhat-et/microshift#277]
#### What would you like to be added:
Create SPEC file for packaging the SELinux policies for running MicroShift on RHEL hosts into an RPM, build RPM, make it available on public repo.

#### Why is this needed:
For running MicroShift on RHEL hosts non-containerized in production, we need SELinux to be set up correctly. RPMs facilitate adding MicroShift into rpm-ostrees. This RPM would be a dependency for the MicroShift RPM.

**Comment by mangelajo** [comment]
Hey, :-) I was starting work on the rpm spec, probably my bad not opening a dedicated issue.

What do you think of making this a sub-package inside the same spec of Microshift itself ?

**Comment by cooktheryan** [comment]
@mangelajo it makes sense because there aren't many rules or restorecons that must be done

**Comment by mangelajo** [comment]
Thanks @cooktheryan will keep you posted on how it goes

**Comment by cooktheryan** [comment]
@mangelajo with this being in copr is there anything remaining?

**Comment by mangelajo** [comment]
This is done, thaks @cooktheryan  :-D 

https://github.com/redhat-et/microshift/blob/f4b3409a3ac9995acaf6bc91d35e92f92a8d34b9/packaging/rpm/microshift.spec#L116
