### ISSUE TITLE
[Enhancement]: Provide RPM for MicroShift

### ISSUE THREAD

**Issue by fzdarsky** [redhat-et/microshift#278]
#### What would you like to be added:
Create SPEC file for packaging MicroShift into an RPM, build RPM, make it available on public repo. That RPM should contain dependencies on the SELinux policies, CRI-O, etc.

#### Why is this needed:
For running MicroShift on RHEL hosts non-containerised in production, we need RPMs that users can embed into rpm-ostrees.

**Comment by cooktheryan** [comment]
@mangelajo same with this one

**Comment by mangelajo** [comment]
I think we can close this, https://copr.fedorainfracloud.org/coprs/g/redhat-et/

Thank's for bug-scrubbing, I'm terrible at this.
