### ISSUE TITLE
[BUG] OS compatibility listing CentOS, but hardcoded 'dnf' in commands

### ISSUE THREAD

**Issue by iranzo** [redhat-et/microshift#374]
#### What happened:

Documentation states:

~~~
Fedora 33/34
CentOS 8 Stream
RHEL 8
CentOS 7
Ubuntu 20.04
~~~

#### What you expected to happen:

Support for CentOS7

#### How to reproduce it (as minimally and precisely as possible):

1. try to launch the installer script
2. it complains about missing `dnf` (as yum is the default in centos7)

#### Environment:

CentOS Linux release 7.7.1908 (Core)

**Comment by alknopfler** [comment]
possible fix here:  https://github.com/redhat-et/microshift/pull/415
