### ISSUE TITLE
[Enhancement]: write reboot test script within CI

### ISSUE THREAD

**Issue by cooktheryan** [redhat-et/microshift#407]
#### What would you like to be added:
We need to ensure that MicroShift can come back online after reboots. 

#### Why is this needed:

Customers will need to be able to handle reboots and power outages

**Comment by alknopfler** [comment]
I'm writing the test to verify the reboot here:
https://github.com/alknopfler/release/tree/testReboot/ci-operator/step-registry/redhat-et/microshift/e2e
