### ISSUE TITLE
[Enhancement]: Docs refactor

### ISSUE THREAD

**Issue by sallyom** [redhat-et/microshift#409]
#### Design Document Link TODO

PR: #<PR Number>

#### What would you like to be added:

We now have a docs site but we need to restructure a bit, we'll have developer docs and user docs, plus, we might update the jekyll theme, or switch to hugo

**Comment by iranzo** [comment]
I'm protected from getting work to do!!! 😂

**Comment by sallyom** [comment]
docs have migrated! still have an open issue to remove docs from this repository, so closing this.
