### ISSUE TITLE
Netlify removal or tuning

### ISSUE THREAD

**Issue by iranzo** [redhat-et/microshift#412]
Now that docs are being moved to another repo, it might be needed to shut off netlify or at least, tune it for 'devel docs' vs 'user-docs'  (related with #411 )

**Comment by mangelajo** [comment]
I manage the netlify account. Which docs are being moved, and to where? :D

**Comment by iranzo** [comment]
User docs to https://github.com/redhat-et/microshift-documentation/  (served now via microshift.io)
