### ISSUE TITLE
[BUG] Volume mount should be for /var/lib/microshift rather than /var/lib

### ISSUE THREAD

**Issue by cooktheryan** [redhat-et/microshift#432]
#### What happened:
Mounting to large of directory space that may not be completely relevant to MicroShift. This also causes some Selinux issues.

#### What you expected to happen:
MicroShift containerized only mounts what is needed

#### How to reproduce it (as minimally and precisely as possible):

1. Deploy MicroShift containerized and verify mount of /var/lib

**Comment by fzdarsky** [comment]
The same argument probably also applies to the `/var/run` bind mount. Do we need anything from that besides `/var/run/crio/crio.sock`? If not, can we bind mount that socket only instead?
