### ISSUE TITLE
[Enhancement]: Move developer documentation back to this repository, point to it from microshift-documentation

### ISSUE THREAD

**Issue by sallyom** [redhat-et/microshift#437]
#### What would you like to be added:

The developer documentation content we believe belongs here, and will be published to `devel.microshift.io`. We can also point to `devel.microshift.io` from `microshift.io` 

#### Why is this needed:

Keeping things organized, separating production use from developer use

**Comment by fzdarsky** [comment]
Moved the design docs back. Developer docs can stay on `microshift.io` for now; we can still move back to this repo later if needed.
