### ISSUE TITLE
[Enhancement]: Should we switch from kubectl to oc

### ISSUE THREAD

**Issue by cooktheryan** [redhat-et/microshift#442]
#### What would you like to be added:
Switch the binary of kubectl to oc

#### Why is this needed:
To stay in line with OpenShift user experience so *oc* should be used.

**Comment by cooktheryan** [comment]
This should be done after docs migrates to the new formatting and we deprecate install.sh

**Comment by fzdarsky** [comment]
@cooktheryan with redhat-et/microshift-documentation#78 and #481 merged, DYT we can close this one?

**Comment by cooktheryan** [comment]
good to close
