### ISSUE TITLE
[BUG] Install script doesn't work

### ISSUE THREAD

**Issue by iranzo** [redhat-et/microshift#446]
#### What happened:

The install script included in the repo is not valid

#### What you expected to happen:

Microshift gets installed
#### How to reproduce it (as minimally and precisely as possible):

1. wget script install.sh
2. sh install.sh

#### Anything else we need to know?:
Install fails because of function name

#### Environment:
- Microshift version (use `microshift version`):
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by cooktheryan** [comment]
closing as we will be deprecating install.sh in the future
