### ISSUE TITLE
[Enhancement]: Add oc client binary to microshift-aio

### ISSUE THREAD

**Issue by cooktheryan** [redhat-et/microshift#474]
#### What would you like to be added:
In the microshift-aio image, replace the upstream kubectl with OKD's oc and kubectl.

#### Why is this needed:
Users may want to use OC commands to do things; version should match OKD's.

**Comment by sallyom** [comment]
OKD version of last rebase: `4.8.0-0.okd-2021-10-10-030117` 
Note: This will need to be updated with every rebase in `images/microshift-aio/Dockerfile` or will need to create a version command to output this for scripting.
