### ISSUE TITLE
[Enhancement]: Update microshift-aio image to allow running contained client tools

### ISSUE THREAD

**Issue by fzdarsky** [redhat-et/microshift#477]
#### What would you like to be added:
In the microshift-aio image, set up kubeconfig such that users can run oc and kubectl directly like this:
```
sudo podman exec -ti microshift oc get all -A
```

#### Why is this needed:
Allows users to access cluster without installing clients locally and without opening a bash session within container.

**Comment by sallyom** [comment]
Since it's same file, adding a commit to set KUBECONFIG in PR #481

**Comment by fzdarsky** [comment]
Closed through #481
