### ISSUE TITLE
[Enhancement]: cri-o RPMs for CentOS 9 Stream

### ISSUE THREAD

**Issue by fzdarsky** [redhat-et/microshift#517]
#### What would you like to be added:
Find cri-o RPMs for CentOS 9 Stream from a trusted source. Alternatively, add own build on COPR under redhat-et/microshift repo.

#### Why is this needed:
Running MicroShift on CentOS 9 Stream on platforms like Jetson.

**Comment by cooktheryan** [comment]
/ assign cooktheryan

**Comment by mangelajo** [comment]
We may want to check if this serves as a workaround for now
```
curl https://raw.githubusercontent.com/cri-o/cri-o/main/scripts/get | bash 
```

**Comment by mangelajo** [comment]
Seems more like a Centos 9 stream issue. Closing
