### ISSUE TITLE
[BUG] If the interface IP changes Microshift stops working

### ISSUE THREAD

**Issue by mangelajo** [redhat-et/microshift#556]
#### What happened:

The openshift-api api endpoints are created based on the existing IP address when microshift starts,
if the IP changes, the kubernetes controller can't connect to the endpoint, and starts failing.

#### What you expected to happen:
Microshift should have recognized the IP change and updated the endpoints, or used a VIP for the API purposes.

#### How to reproduce it (as minimally and precisely as possible):

1. Assign an IP address to the MicroShift host
2. Start MicroShift
3. Change the IP address
4. MicroShift stops working
5. restart MicroShift
6. MicroShift still not working

**Comment by DanielFroehlich** [comment]
workaround:
1. list endpoints: `oc get endpoints -A`
2. identify endpoints with the wrong (old) IP adress
3. `oc edit`  the endpoints and change to new ip adress
4.  `systemctl restart microshift`
