### ISSUE TITLE
[Enhancement]: why not join rancher together

### ISSUE THREAD

**Issue by cnmade** [redhat-et/microshift#566]
https://github.com/rancher-sandbox/rancher-desktop

I like your microshift idea, and i noticed  rancher developed a very similar things. 

I want to share my point.
actually, you can coperation with Rancher indeed.

A full featured docker desktop alternative.

a onestep full stack (OpenShift + Kubernetes) application. 

One install, full feature include, you can choice which components to enable or not.

rancher-desktop really good idea.

for now days: there a too many container products. but too small , too dispersion

Why not just provided a real usable product.   like the docker desktop.

**Comment by fzdarsky** [comment]
Thank you for your suggestion @cnmade. I absolutely agree on the value of collaboration in open source community projects (i.e. Kubernetes in this case) and Rancher and us _are_ collaborating well there. If your comment was instead referring to merging distributions/products from different vendors, that'd be much more difficult ask.

Please note, also, that it is not MicroShift's goal to produce a desktop environment for Kubernetes development, though one could certainly build one on top of it.
