### ISSUE TITLE
Unable to connect to kubelet 

### ISSUE THREAD

**Issue by jimcadden** [redhat-et/microshift#602]
#### What happened:
I can deploy pods but cannot connect to containers or view container logs. 

```
$ oc get node
NAME                     STATUS   ROLES    AGE    VERSION
pirpipi.localrpi.local   Ready    <none>   4d1h   v1.21.0

$ oc get pods -A
NAMESPACE                       NAME                                  READY   STATUS    RESTARTS   AGE
default                         apache                                1/1     Running   0          72m
kube-system                     kube-flannel-ds-zxlqs                 1/1     Running   10         4d1h
kubevirt-hostpath-provisioner   kubevirt-hostpath-provisioner-hmq8v   1/1     Running   1          2d22h
openshift-dns                   dns-default-m9rhw                     2/2     Running   18         3d22h
openshift-dns                   node-resolver-b24jz                   1/1     Running   9          3d22h
openshift-ingress               router-default-85bcfdd948-p2mc9       1/1     Running   21         4d1h
openshift-service-ca            service-ca-7764c85869-8qsn6           1/1     Running   9          3d22h


$ oc logs apache
Error from server: Get "https://pirpipi.localrpi.local:10250/containerLogs/default/apache/apache": dial tcp: lookup pirpipi.localrpi.local on 192.168.1.1:53: no such host

$ oc exec --stdin --tty apache -- /bin/bash
Error from server: error dialing backend: dial tcp: lookup pirpipi.localrpi.local on 192.168.1.1:53: no such host 

$ netstat -tulpn | grep 10250
tcp6       0      0 :::10250                :::*                    LISTEN      1707696/microshift

$ hostname
pirpipi.localrpi.local

$ ping pirpipi.localrpi.local -c 1
PING pirpipi.localrpi.local(pirpipi.localrpi.local (fe80::b77e:2a88:4a4e:4bda%wlan0)) 56 data bytes
64 bytes from pirpipi.localrpi.local (fe80::b77e:2a88:4a4e:4bda%wlan0): icmp_seq=1 ttl=64 time=0.271 ms

--- pirpipi.localrpi.local ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.271/0.271/0.271/0.000 ms
```

#### How to reproduce it (as minimally and precisely as possible):

1. Fedora 35 for `arm64` 
2. Kernel `5.15.21` installed w/ Raspberry Pi device drivers  
3. Latest MicroShift rpm packages 

#### Anything else we need to know?:

It's probably a network configuration issue on my end. Any ideas?   

#### Environment:
- Microshift version (use `microshift version`): MicroShift Version: 4.8.0-0.microshift-2022-02-02-194009, Base OKD Version: 4.8.0-0.okd-2021-10-10-030117
- Hardware configuration: arm64 Raspberry Pi 4 
- OS (e.g: `cat /etc/os-release`): Fedora 35 
- Kernel (e.g. `uname -a`): 5.15.21-v8+ 
- Others:

#### Relevant Logs 

Maybe this k8s event is related?
```
kubevirt-hostpath-provisioner   60m         Warning   FailedCreatePodSandBox    pod/kubevirt-hostpath-provisioner-hmq8v   Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_kubevirt-hostpath-provisioner-hmq8v_kubevirt-hostpath-provisioner_e6a08fb4-cda3-4747-beeb-cd6febf2dbff_0(f5f17a2c33a330084a49cd1a8d5fe9740c5ba04b0d995f6229b53b90828c5419): error adding pod kubevirt-hostpath-provisioner_kubevirt-hostpath-provisioner-hmq8v to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
```

**Comment by MichaelWasher** [comment]
++ I have the same issue. I'm not very familiar with the arch of Microshift, but it looks like KubeAPI/OpenShiftAPI/Kubelet are all bundled together in same binary / netns. 
After having a quick poke, looks like the APIserver is trying to do full DNS resolution for the local hostname (requesting the gateway DNS for details). I guess you could get it working by adding something there, but it can all be bypassed by just skipping the lookup chain by adding a result in `/etc/hosts`.

**Comment by MichaelWasher** [comment]
Scratch that, it looks like it's this line in the nsswitch.conf:
~~~
hosts:      files dns myhostname
~~~

But according to the [manpage](https://man7.org/linux/man-pages/man5/nsswitch.conf.5.html), changes to `/etc/nsswitch.conf` will most likely require a restart of the process to become effective. This will bring it's own problems as it's PID 1 in the NS.

```
       Within each process that uses nsswitch.conf, the entire file is
       read only once.  If the file is later changed, the process will
       continue using the old configuration.
```

**Comment by jimcadden** [comment]
> it can all be bypassed by just skipping the lookup chain by adding a result in /etc/hosts.

Thanks @MichaelWasher, adding the entry to `/etc/hosts` solved my issue.

**Comment by MichaelWasher** [comment]
Turns out when I looked at the UBI base, that's where it comes from. So I'm surprised that there are not more complaints about it.
