### ISSUE TITLE
[BUG] [AIO] Unhealthy DNS pod

### ISSUE THREAD

**Issue by oglok** [redhat-et/microshift#606]
#### What happened:

Following instructions on microshift.io for AIO on Linux:
https://microshift.io/docs/getting-started/#using-microshift-for-application-development

All infra pods get scheduled and running except the default DNS pod (1/2):

```
openshift-dns                   dns-default-lkjwg                      1/2     Running   5          27m   10.42.0.2   a92cc98eb64a   <none>           <none>
```
Logs: 

```sudo podman exec -ti microshift crictl logs 3b00b7b409c7d
WARN[0000] Error validating CNI config file /etc/cni/net.d/10-flannel.conflist: [failed to find plugin "flannel" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]] 
.:5353
[INFO] plugin/reload: Running configuration MD5 = eb791f1fb4e1f964e4a7377f6b122c87
CoreDNS-1.8.1
linux/amd64, go1.16.1, 
W0228 17:14:27.051185       1 reflector.go:436] github.com/coredns/coredns/plugin/kubernetes/controller.go:399: watch of *v1.EndpointSlice ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0228 17:14:27.051214       1 reflector.go:436] github.com/coredns/coredns/plugin/kubernetes/controller.go:406: watch of *v1.Namespace ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0228 17:14:27.051225       1 reflector.go:436] github.com/coredns/coredns/plugin/kubernetes/controller.go:395: watch of *v1.Service ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
```

#### What you expected to happen:

All infra services must be up and running.

#### How to reproduce it (as minimally and precisely as possible):

1. Follow https://microshift.io/docs/getting-started/#using-microshift-for-application-development

#### Environment:
- Microshift version (use `microshift version`):
MicroShift Version: 4.8.0-0.microshift-unknown
Base OKD Version: 4.8.0-0.okd-2021-10-10-030117
- Hardware configuration:
Lenovo X1 Carbon 
- OS (e.g: `cat /etc/os-release`):
Fedora 35
- Kernel (e.g. `uname -a`):
Linux fedora.oglok.net 5.16.8-200.fc35.x86_64 #1 SMP PREEMPT Tue Feb 8 20:58:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

- Others:

**Comment by christianh814** [comment]
I also ran into this (DNS not working at all)
