### ISSUE TITLE
[BUG] On a Raspberry PI 400,  router pod goes into a crash loop

### ISSUE THREAD

**Issue by itroyano** [redhat-et/microshift#607]
#### What happened:

`openshift-ingress               router-default-85bcfdd948-qzt8t       0/1     CrashLoopBackoff`

Reason for it, from the logs -

`E0301 11:05:31.308268       1 reflector.go:138] pkg/router/controller/factory/factory.go:125: Failed to watch *v1.Route: failed to list *v1.Route: the server is currently unable to handle the request (get routes.route.openshift.io)`

#### How to reproduce it (as minimally and precisely as possible):

Install Microshift on the hardware provided below.

#### Anything else we need to know?:

The issue reproduces when trying to get all APIs -

`oc api-resources | grep -i route`

`error: unable to retrieve the complete list of server APIs: apps.openshift.io/v1: the server is currently unable to handle the request, build.openshift.io/v1: the server is currently unable to handle the request, image.openshift.io/v1: the server is currently unable to handle the request, project.openshift.io/v1: the server is currently unable to handle the request, route.openshift.io/v1: the server is currently unable to handle the request, template.openshift.io/v1: the server is currently unable to handle the request, user.openshift.io/v1: the server is currently unable to handle the request`

#### Environment:
`MicroShift Version: 4.8.0-0.microshift-unknown
Base OKD Version: 4.8.0-0.okd-2021-10-10-030117`

- Hardware configuration:  Raspberry PI 400. 64 bit OS.

- OS (e.g: `cat /etc/os-release`): 
`PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`

- Kernel (e.g. `uname -a`): `5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux`

#### Relevant Logs 

attached in description.

**Comment by mangelajo** [comment]
This was probably due to an IP change in the container of microshift, we have now bugfixes and recommendations in place. (Like pausing the AIO container instead of stopping)

Please re-open if the bug is persisting
