### ISSUE TITLE
[Enhancement]: Enable multi-user modes using oc login or the OpenShift APIs

### ISSUE THREAD

**Issue by Neirth** [redhat-et/microshift#632]
#### What would you like to be added:

The option to enable multi-user spaces using an htpasswd file or using the UNIX users of the node (so that it can later be linked to an LDAP system).

#### Why is this needed:

I see it necessary to expose this option given the danger that operations with the kubeadmin user can entail. In the Standard version of Openshift this is configurable through an htpasswd, with an SSO system, or with LDAP.

In addition to the fact that if exposing the technology to edge environments is being explored, such as a telephone antenna, it will easily allow a password rotation.

**Comment by oglok** [comment]
Hello @Neirth , 

MicroShift at this current moment only integrates the OAuth API server in order to provide specific resources like "projects" for sake of compatibility. The project is highly oriented to edge computing use cases, where devices will be completely headless (no screen, no keyboard, not even ssh in most of the environments). The cluster management will be done via ACM (or similar) so multi-user should be unlikely. Is there a specific use case you have in mind? 

Thanks!

**Comment by Neirth** [comment]
Hello @oglok,

Thanks for you quickly response!

I had in mind the following case, in an edge computing environment, I have different projects and types of operators that I want to be able to manipulate the cluster through the oc command or with a web console that can be developed by the team in charge of it.  

To develop the example a little more, we are going to think that it is a telephony cell.  

I may at some point wish that the pods that are in charge of managing everything related to the reception of the 5G band allocate it to a single team, and that another team is in charge of managing the pods for the 4G band.  And in no case, that they can see, for example, a deployment of a prometheus agent because that can be dedicated to the support team, much less that they can touch the pods related to the Kubernetes API.

Really, I highly value your product for these capabilities it brings, also believing that it is a plus that few have and that, in my personal opinion, it is quite necessary.  In fact, some time ago I was evaluating your commercial project for edge environments with this granularity in the permissions that each user had.

Therefore, here is this issue, honestly it is one of the thousands that you can find with edge environments, and I think this can be a feature that can be configured in case it is needed.

Thanks for your attention!

**Comment by Neirth** [comment]
Hello again @oglok!

It is a pleasure to see this good feedback from you, therefore I have to thank you very much.  

RBAC can limit the authorization that a developer or operator has on a certain type of project / namespace, in that part the truth is that it fulfills its function.  

But in neither case is RBAC intended for a user authentication process, in any case, it can be authenticated with the kubeconfig, but we will both agree that the administration of that kubeconfig is something quite delicate, more on remote environments.  

Openshift already had quite good mechanisms to manage these certificates.  

That is why I told you to recover such a mechanism, perhaps removing the SSO part against providers such as Github or some cloud provider and putting an htpasswd mechanism or the unix users, which can already be linked with the modules that are desired through the PAM modules.  

Hence I think you could save quite a few parts to reimplement.  

Although, as you mentioned, this must be a secondary objective with respect to the MVP (Minimal Valuable Product) that you are wishing to achieve, as I say, this is for cases where you do not want to have an agent (pod) that can internally manipulate the state of the cluster per project requirements.

And to conclude, thank you very much for the dedication and the prompt responses that you are receiving in this thread, it is very much appreciated.  

Have a nice day!

**Comment by mangelajo** [comment]
This is something not currently in our roadmap for far edge devices.
