### ISSUE TITLE
Integrate into OpenShift CI

### ISSUE THREAD

**Issue by fzdarsky** [redhat-et/microshift#79]
Integrate this repo into OpenShift CI, running at least go fmt, go vet, and go test as well as uploading image builds. Remove travis.

Blocked on https://github.com/redhat-et/microshift/issues/75.

**Comment by copejon** [comment]
The build ci constructs to images, one containing a linux-amd64 binary and the other a linux-arm64 binary.  I've pinged the reviewers and am waiting for an lgtm.

**Comment by copejon** [comment]
PR #18830 has merged.
