### ISSUE TITLE
Add firewalld rules

### ISSUE THREAD

**Issue by fzdarsky** [redhat-et/microshift#86]

**Comment by rootfs** [comment]
for both single and multi-node setup

**Comment by copejon** [comment]
@fzdarsky @rootfs Is there more to add beyond #128 or can we close this issue?

**Comment by rootfs** [comment]
cc @cooktheryan

**Comment by cooktheryan** [comment]
@rootfs I know we are good with single node. Do we have multi-node established yet?

**Comment by rootfs** [comment]
@cooktheryan let's solve the multi-node case when it is a thing :D

**Comment by cooktheryan** [comment]
K. Then let's just close this as is then
